### ISSUE TITLE
The code doesn't work at all

### ISSUE THREAD

**Issue by jindongwang** [pumpikano/tf-dann#16]
Hi there,
I've downloaded the code and dataset, but I couldn't run the ipynb file at all. It seems in every block, there is a mistake.
My platform is Windows 10 + python 3.6 + tensorflow 1.3.0.
I also check with my Mac OS 10.13.0 + python 3.6 + tensorflow 1.3.0.
Coule you please rerun and check the code yourself?

**Comment by pumpikano** [comment]
Yeah, this was written for Python 2.7 with Tensorflow 0.9. It is certainly very out of date at this point, but unfortunately I don't have time to update it at the moment. If you happen to have time to update it for TF 1.3, that would be greatly appreciated!

**Comment by jindongwang** [comment]
Ok, I'll look into it. Thanks again for your support!

**Comment by jindongwang** [comment]
And, I think it will be great if you can add the version of the required environments to the readme.md.

**Comment by jindongwang** [comment]
@pumpikano I have successfully run the code in Python 3.x + Tensorflow 1.3.0. Can I pull request and change the code so you can merge them?
Really like to be of help. I understand a good code tutorial is of great importance to those folks like me.

**Comment by pumpikano** [comment]
Sorry it's taken me a while to get to this - I updated for 3.x and Tensorflow>=1.0. Please try it out and let me know if there are still issues.
