### ISSUE TITLE
Improving results for MNIST-M?

### ISSUE THREAD

**Issue by zumpchke** [pumpikano/tf-dann#2]
I was able to reproduce the main result on the mnist-m dataset (basically~ 0.5 acc -> ~0.7). What are architectural strategies available to improve it even further?

**Comment by pumpikano** [comment]
I can refer you to two related works that offer interesting structural ideas.

[Deep Reconstruction-Classification Networks for Unsupervised Domain Adaptation](https://arxiv.org/abs/1607.03516) is directly comparable to this work. [Towards Principled Unsupervised Learning](https://arxiv.org/abs/1511.06440) looks at the idea of unsupervised domain alignment in their experiments. Both of these ideas have structural ideas that might help improve this task.

I hope this is helpful!

**Comment by zumpchke** [comment]
Thanks. BTW, I implemented this repo in Keras.

https://github.com/fchollet/keras/pull/4031
