### ISSUE TITLE
May I open source my code on Multi-Soucrce Domain Adaptation?

### ISSUE THREAD

**Issue by daoyuan98** [pumpikano/tf-dann#28]
Hi, Thank you so much for your code. I am interested in domain adaptation and have run your code. I also implemented several experiments of Multi-Source Domain Adaptation. As an apprentice in tensorflow, I borrowed  several lines of your code. I wonder may I open source my code on Multi-Source Domain Adaptation? Thank you very much.

**Comment by pumpikano** [comment]
Of course you can open source your project! I'd be interested in seeing it. If you think you borrowed enough code merit it, I'd appreciate an acknowledgement in the project.

**Comment by daoyuan98** [comment]
Thanks！ Here is the repo. https://github.com/daoyuan98/MSDA
