### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by saadirtza** [pumpikano/tf-dann#3]
Hi,

Thanks for sharing the code. I m new to tensorflow.. i have developed the MNIST database as u suggested in your code. Can you please help me to run the adaptation code? Which file is actually is the main code for tf-dann

Many thanks 
Regards
Saad

**Comment by pumpikano** [comment]
Hey @saadirtza, two two .ipynb files contain two simple experiments. You should be able to run these notebooks with Jupyter notebook in an python environment with Tensorflow as the dependencies specified in `requirements.txt`.

**Comment by saadirtza** [comment]
it worked. Thanks alot.
