### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by albertz** [pumpikano/tf-dann#33]
Thank you for this nice project!

We ([RETURNN](https://github.com/rwth-i6/returnn)) have made use of some code snippets from this project, esp the `FlipGradientBuilder`. (Or rather, after reading your code, I was not really sure how to write it in a different way.)

Is it possible that you add a licence to your code? Like Apache-2.0 or MIT?

https://github.com/rwth-i6/returnn/issues/796

**Comment by pumpikano** [comment]
Certainly, this was a oversight from the beginning. I've added MIT license.

I would point out that this implementation may not be the best way to implement flip gradient with the modern TF API. You may want to look at `tf.custom_gradient` https://www.tensorflow.org/api_docs/python/tf/custom_gradient, though I haven't used it myself.

All the best.

**Comment by albertz** [comment]
Thanks a lot!
