### ISSUE TITLE
How to compute prediction and transformed features?

### ISSUE THREAD

**Issue by saadirtza** [pumpikano/tf-dann#6]
Hi Pumpikano,

thanks for answering my questions. i am trying to get the prediction values instead of predicted labels and accuracy, in this regard, i have modify the code as
Changed the line 
correct_label_pred = tf.equal(tf.argmax(model.classify_labels, 1), tf.argmax(model.pred, 1))
to 
label_acc_lk = model.pred

i am getting the predictions, just wondering is it correct to do so?

Many thanks

Regards
Saad

**Comment by pumpikano** [comment]
I don't understand your question.

`model.pred` is the softmax outputs, `tf.argmax(model.pred, 1)` would give you the highest probability label, and `correct_label_pred` tells you which predictions are correct.

**Comment by saadirtza** [comment]
Thanks Pumpikano.. i understand now..

Regards
