### ISSUE TITLE
Adapted feature extraction

### ISSUE THREAD

**Issue by saadirtza** [pumpikano/tf-dann#7]
Hi Pumpikano,

With your help, i am able to get the prediction values, (thanks)..

but the performance is very poor. so i thought to look at the adapted features on my database. The features are all zeros. 
source_acc, target_acc, d_acc, dann_emb = train_and_evaluate('dann', graph, model)

in the above line 'dann_emb' is the adapted features and they are all zeros. There is no error or warning in the code.

Can you please suggest where the problem might be? Thanks alot

Best Regards
Saad

**Comment by saadirtza** [comment]
After some iteration of DANN training, the values of batch loss is 0.61 but dloss and ploss are NAN..

Is this because i am not feeding the data properly or network configuration is not good?

Thanks 

Regards

**Comment by saadirtza** [comment]
That was the issue with selection of initial learning paramter i.e 'lr' in the code.. Can you please suggest any tutorial on how to select this parameter for good performance?

Thanks & Regards

**Comment by pumpikano** [comment]
These lecture slides are a "classic" reference for intuitions and tips for setting learning rates: http://www.cs.toronto.edu/~tijmen/csc321/slides/lecture_slides_lec6.pdf
